language: csharp
solution: MailKit.Net45.sln
install:
  - git submodule update --init --recursive
  - nuget restore submodules/MimeKit/MimeKit.Net45.sln
  - nuget restore MailKit.Net45.sln
script:
  - msbuild /p:Configuration=Debug MailKit.Net45.sln
  - mono ./packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe UnitTests/bin/Debug/UnitTests.dll
